# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-14 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20160708_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/banner_categories'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/data'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/data'),
        ),
    ]
